"""Offline complement-arbitrage candidate models."""

from edmn_trader.arb.approval import (
    ManualApprovalDecision,
    PendingManualApproval,
    create_pending_approval,
    verify_manual_approval,
    write_approval_markdown,
    write_approval_records_jsonl,
    write_pending_approval_file,
)
from edmn_trader.arb.complement import (
    ComplementArbCandidate,
    ComplementArbDecision,
    ComplementArbInput,
    compute_canonical_yes_side_cross_candidate,
    compute_kalshi_complement_candidate,
)
from edmn_trader.arb.fill_simulation import (
    FillPolicy,
    FillSimulationInput,
    FillSimulationResult,
    simulate_taker_fill,
    write_fill_simulation_jsonl,
    write_fill_simulation_markdown,
)
from edmn_trader.arb.long_term_validation import (
    RollingValidationReport,
    RollingValidationWindow,
    build_rolling_validation_report,
    render_rolling_validation_markdown,
    write_rolling_validation_json,
    write_rolling_validation_jsonl,
    write_rolling_validation_markdown,
)
from edmn_trader.arb.monitoring import (
    DailyValidationReport,
    build_daily_validation_report,
    write_daily_validation_jsonl,
    write_daily_validation_markdown,
)
from edmn_trader.arb.paper_engine import (
    PaperOrderLeg,
    PaperOrderProposal,
    PaperRiskPreview,
    propose_paper_order,
    write_paper_order_markdown,
    write_paper_order_proposals,
)
from edmn_trader.arb.paper_ledger import (
    PaperLedgerMismatch,
    PaperLedgerPosition,
    PaperLedgerSourceHash,
    PaperLedgerState,
    replay_paper_ledger,
    write_paper_ledger_jsonl,
    write_paper_ledger_markdown,
)
from edmn_trader.arb.risk import (
    ComplementRiskDecision,
    ComplementRiskInput,
    evaluate_complement_risk,
    risk_input_from_record,
    write_complement_risk_jsonl,
    write_complement_risk_markdown,
)
from edmn_trader.arb.scanner import (
    ComplementScanRecord,
    ComplementScanReport,
    render_markdown_summary,
    scan_fixture_file,
    scan_snapshot_jsonl_file,
    write_jsonl_report,
    write_markdown_summary,
)

__all__ = [
    "ComplementArbCandidate",
    "ComplementArbDecision",
    "ComplementArbInput",
    "ComplementRiskDecision",
    "ComplementRiskInput",
    "ComplementScanRecord",
    "ComplementScanReport",
    "DailyValidationReport",
    "FillPolicy",
    "FillSimulationInput",
    "FillSimulationResult",
    "ManualApprovalDecision",
    "PaperOrderLeg",
    "PaperOrderProposal",
    "PaperRiskPreview",
    "PendingManualApproval",
    "PaperLedgerMismatch",
    "PaperLedgerPosition",
    "PaperLedgerSourceHash",
    "PaperLedgerState",
    "RollingValidationReport",
    "RollingValidationWindow",
    "compute_canonical_yes_side_cross_candidate",
    "compute_kalshi_complement_candidate",
    "create_pending_approval",
    "build_daily_validation_report",
    "build_rolling_validation_report",
    "evaluate_complement_risk",
    "propose_paper_order",
    "risk_input_from_record",
    "replay_paper_ledger",
    "render_markdown_summary",
    "render_rolling_validation_markdown",
    "scan_fixture_file",
    "scan_snapshot_jsonl_file",
    "simulate_taker_fill",
    "verify_manual_approval",
    "write_approval_markdown",
    "write_approval_records_jsonl",
    "write_daily_validation_jsonl",
    "write_daily_validation_markdown",
    "write_fill_simulation_jsonl",
    "write_fill_simulation_markdown",
    "write_complement_risk_jsonl",
    "write_complement_risk_markdown",
    "write_jsonl_report",
    "write_markdown_summary",
    "write_paper_order_markdown",
    "write_paper_order_proposals",
    "write_paper_ledger_jsonl",
    "write_paper_ledger_markdown",
    "write_pending_approval_file",
    "write_rolling_validation_json",
    "write_rolling_validation_jsonl",
    "write_rolling_validation_markdown",
]
