from __future__ import annotations

import json
from pathlib import Path

import pytest

from edmn_trader.data.jsonl import write_jsonl_records
from edmn_trader.scripts.paper_report_pack import (
    PaperReportPackInput,
    generate_paper_report_pack,
    main,
)

FIXTURES = Path(__file__).parent / "fixtures"


def test_paper_report_pack_combines_stage_7_metrics_and_sec_facts(tmp_path: Path) -> None:
    log_path = _write_stage_6_log(tmp_path)
    output_dir = tmp_path / "pack"
    manifest_path = _write_report_input_manifest(tmp_path)

    pack = generate_paper_report_pack(
        PaperReportPackInput(
            market_maker_logs=(log_path,),
            sec_companyfacts=(FIXTURES / "sec_companyfacts_aapl.json",),
            report_input_manifest=manifest_path,
            output_dir=output_dir,
        )
    )

    assert pack.stage7_report.supplied_fills == 0
    assert pack.sec_fact_count == 2
    assert pack.manifest_entry_count == 1
    text = (output_dir / "report_pack.md").read_text(encoding="utf-8")
    assert "Observed Stage 7 Attribution" in text
    assert "frames | 1" in text
    assert "Fill assumptions | not supplied" in text
    assert "Local Source Inventory" in text
    assert "market_maker.jsonl" in text
    assert "sec_companyfacts_aapl.json" in text
    assert "Report Input Manifest" in text
    assert "Local Stage 7 report" in text
    assert "local file generated by test" in text
    assert "SEC Fundamentals" in text
    assert "Apple Inc." in text
    assert "Revenues" in text
    assert "does not rank securities" in text
    assert "does not claim profitability" in text
    assert "trading signal" not in text.lower()


def test_paper_report_pack_marks_missing_sec_fundamentals_not_supplied(tmp_path: Path) -> None:
    output_dir = tmp_path / "pack"

    generate_paper_report_pack(
        PaperReportPackInput(
            market_maker_logs=(_write_stage_6_log(tmp_path),),
            output_dir=output_dir,
        )
    )

    text = (output_dir / "report_pack.md").read_text(encoding="utf-8")
    assert "SEC fundamentals | not supplied" in text
    assert "SEC companyfacts | not supplied" in text
    assert "Fills | not supplied" in text
    assert "Report input manifest | not supplied" in text
    assert "missing optional inputs are reported as not supplied" in text


def test_paper_report_pack_rejects_unsafe_manifest_inputs(tmp_path: Path) -> None:
    remote_manifest_path = _write_report_input_manifest(
        tmp_path,
        local_path="https://example.com/data.json",
    )
    with pytest.raises(ValueError, match="remote URL"):
        generate_paper_report_pack(
            PaperReportPackInput(
                market_maker_logs=(_write_stage_6_log(tmp_path),),
                report_input_manifest=remote_manifest_path,
                output_dir=tmp_path / "remote-pack",
            )
        )

    secret_manifest_path = _write_report_input_manifest(tmp_path, api_key="should-not-be-read")
    with pytest.raises(ValueError, match="secret-like"):
        generate_paper_report_pack(
            PaperReportPackInput(
                market_maker_logs=(_write_stage_6_log(tmp_path),),
                report_input_manifest=secret_manifest_path,
                output_dir=tmp_path / "pack",
            )
        )


def test_paper_report_pack_renders_local_run_comparison_input(tmp_path: Path) -> None:
    comparison_path = _write_run_comparison_descriptor(tmp_path)
    manifest_path = _write_report_input_manifest(
        tmp_path,
        local_path=comparison_path.name,
        input_kind="local_run_comparison",
        display_label="Local dry-run comparison",
    )
    output_dir = tmp_path / "pack"

    pack = generate_paper_report_pack(
        PaperReportPackInput(
            market_maker_logs=(_write_stage_6_log(tmp_path),),
            report_input_manifest=manifest_path,
            output_dir=output_dir,
        )
    )

    assert pack.run_comparison_count == 2
    text = (output_dir / "report_pack.md").read_text(encoding="utf-8")
    assert "Local Run Comparison" in text
    assert "baseline dry run" in text
    assert "demo opt-in dry run" in text
    assert "observed decisions" in text
    assert "fills" in text
    assert "local/offline comparison metadata only" in text
    assert "best run" not in text.lower()
    assert "recommend" not in text.lower()


def test_paper_report_pack_marks_missing_optional_run_comparison_not_supplied(
    tmp_path: Path,
) -> None:
    manifest_path = _write_report_input_manifest(
        tmp_path,
        local_path="missing-run-comparison.json",
        input_kind="local_run_comparison",
        display_label="Missing local comparison",
    )
    output_dir = tmp_path / "pack"

    generate_paper_report_pack(
        PaperReportPackInput(
            market_maker_logs=(_write_stage_6_log(tmp_path),),
            report_input_manifest=manifest_path,
            output_dir=output_dir,
        )
    )

    text = (output_dir / "report_pack.md").read_text(encoding="utf-8")
    assert "Local Run Comparison" in text
    assert "Missing local comparison | not supplied" in text


def test_paper_report_pack_rejects_unsafe_run_comparison_descriptor(tmp_path: Path) -> None:
    secret_descriptor_path = _write_run_comparison_descriptor(
        tmp_path,
        extra_run_field={"access_token": "should-not-be-read"},
    )
    secret_manifest_path = _write_report_input_manifest(
        tmp_path,
        local_path=secret_descriptor_path.name,
        input_kind="local_run_comparison",
    )
    with pytest.raises(ValueError, match="secret-like"):
        generate_paper_report_pack(
            PaperReportPackInput(
                market_maker_logs=(_write_stage_6_log(tmp_path),),
                report_input_manifest=secret_manifest_path,
                output_dir=tmp_path / "secret-pack",
            )
        )

    remote_descriptor_path = _write_run_comparison_descriptor(
        tmp_path,
        run_local_path="https://example.com/report.md",
    )
    remote_manifest_path = _write_report_input_manifest(
        tmp_path,
        local_path=remote_descriptor_path.name,
        input_kind="local_run_comparison",
    )
    with pytest.raises(ValueError, match="remote URL"):
        generate_paper_report_pack(
            PaperReportPackInput(
                market_maker_logs=(_write_stage_6_log(tmp_path),),
                report_input_manifest=remote_manifest_path,
                output_dir=tmp_path / "remote-comparison-pack",
            )
        )


def test_paper_report_pack_renders_local_validation_summary_input(tmp_path: Path) -> None:
    validation_path = _write_validation_summary_descriptor(tmp_path)
    manifest_path = _write_report_input_manifest(
        tmp_path,
        local_path=validation_path.name,
        input_kind="local_validation_summary",
        display_label="Local validation summary",
    )
    output_dir = tmp_path / "pack"

    pack = generate_paper_report_pack(
        PaperReportPackInput(
            market_maker_logs=(_write_stage_6_log(tmp_path),),
            report_input_manifest=manifest_path,
            output_dir=output_dir,
        )
    )

    assert pack.validation_summary_count == 2
    text = (output_dir / "report_pack.md").read_text(encoding="utf-8")
    assert "Local Validation Summary" in text
    assert "pytest" in text
    assert "ruff check ." in text
    assert "pass" in text
    assert "skipped" in text
    assert "pytest.log" in text
    assert "metadata about checks already run" in text
    assert "recommend" not in text.lower()


def test_paper_report_pack_marks_missing_optional_validation_summary_not_supplied(
    tmp_path: Path,
) -> None:
    manifest_path = _write_report_input_manifest(
        tmp_path,
        local_path="missing-validation-summary.json",
        input_kind="local_validation_summary",
        display_label="Missing validation summary",
    )
    output_dir = tmp_path / "pack"

    generate_paper_report_pack(
        PaperReportPackInput(
            market_maker_logs=(_write_stage_6_log(tmp_path),),
            report_input_manifest=manifest_path,
            output_dir=output_dir,
        )
    )

    text = (output_dir / "report_pack.md").read_text(encoding="utf-8")
    assert "Local Validation Summary" in text
    assert "Missing validation summary | not supplied" in text


def test_paper_report_pack_rejects_unsafe_validation_summary_descriptor(
    tmp_path: Path,
) -> None:
    secret_descriptor_path = _write_validation_summary_descriptor(
        tmp_path,
        extra_check_field={"api_secret": "should-not-be-read"},
    )
    secret_manifest_path = _write_report_input_manifest(
        tmp_path,
        local_path=secret_descriptor_path.name,
        input_kind="local_validation_summary",
    )
    with pytest.raises(ValueError, match="secret-like"):
        generate_paper_report_pack(
            PaperReportPackInput(
                market_maker_logs=(_write_stage_6_log(tmp_path),),
                report_input_manifest=secret_manifest_path,
                output_dir=tmp_path / "secret-validation-pack",
            )
        )

    remote_descriptor_path = _write_validation_summary_descriptor(
        tmp_path,
        artifact_path="https://example.com/pytest.log",
    )
    remote_manifest_path = _write_report_input_manifest(
        tmp_path,
        local_path=remote_descriptor_path.name,
        input_kind="local_validation_summary",
    )
    with pytest.raises(ValueError, match="remote URL"):
        generate_paper_report_pack(
            PaperReportPackInput(
                market_maker_logs=(_write_stage_6_log(tmp_path),),
                report_input_manifest=remote_manifest_path,
                output_dir=tmp_path / "remote-validation-pack",
            )
        )


def test_paper_report_pack_cli_writes_markdown(tmp_path: Path, capsys, monkeypatch) -> None:
    output_dir = tmp_path / "pack"
    manifest_path = _write_report_input_manifest(tmp_path)
    monkeypatch.setattr(
        "sys.argv",
        [
            "paper_report_pack",
            "--market-maker-log",
            str(_write_stage_6_log(tmp_path)),
            "--sec-companyfacts",
            str(FIXTURES / "sec_companyfacts_aapl.json"),
            "--report-input-manifest",
            str(manifest_path),
            "--output-dir",
            str(output_dir),
        ],
    )

    main()

    assert (output_dir / "report_pack.md").exists()
    output = capsys.readouterr().out
    assert "report_pack_output=" in output
    assert "sec_facts=2" in output
    assert "manifest_inputs=1" in output


def _write_report_input_manifest(
    tmp_path: Path,
    *,
    local_path: str = "stage7_attribution.md",
    input_kind: str = "stage7_report",
    display_label: str = "Local Stage 7 report",
    api_key: str | None = None,
) -> Path:
    manifest_path = tmp_path / "manifest.json"
    entry = {
        "local_path": local_path,
        "input_kind": input_kind,
        "display_label": display_label,
        "rights_note": "local file generated by test",
        "assumption_scope": "descriptive only",
        "required": False,
    }
    if api_key is not None:
        entry["api_key"] = api_key
    manifest_path.write_text(
        json.dumps(
            {
                "inputs": [entry]
            }
        ),
        encoding="utf-8",
    )
    return manifest_path


def _write_run_comparison_descriptor(
    tmp_path: Path,
    *,
    run_local_path: str = "stage7_attribution.md",
    extra_run_field: dict[str, str] | None = None,
) -> Path:
    descriptor_path = tmp_path / "run_comparison.json"
    first_run = {
        "run_name": "baseline dry run",
        "local_path": run_local_path,
        "observed_decision_count": 3,
        "not_supplied_inputs": ["fills"],
        "limitation_note": "local/offline comparison metadata only",
    }
    if extra_run_field:
        first_run.update(extra_run_field)
    descriptor_path.write_text(
        json.dumps(
            {
                "runs": [
                    first_run,
                    {
                        "run_name": "demo opt-in dry run",
                        "local_path": "report_pack.md",
                        "observed_decision_count": 4,
                        "not_supplied_inputs": [],
                        "limitation_note": "fake adapter only",
                    },
                ]
            }
        ),
        encoding="utf-8",
    )
    return descriptor_path


def _write_validation_summary_descriptor(
    tmp_path: Path,
    *,
    artifact_path: str = "pytest.log",
    extra_check_field: dict[str, str] | None = None,
) -> Path:
    descriptor_path = tmp_path / "validation_summary.json"
    first_check = {
        "command_label": "pytest",
        "status": "pass",
        "artifact_path": artifact_path,
        "observed_at": "2026-06-24T22:00:00-07:00",
        "limitation_note": "metadata about checks already run",
    }
    if extra_check_field:
        first_check.update(extra_check_field)
    descriptor_path.write_text(
        json.dumps(
            {
                "checks": [
                    first_check,
                    {
                        "command_label": "ruff check .",
                        "status": "skipped",
                        "artifact_path": "ruff.log",
                        "observed_at": "2026-06-24T22:01:00-07:00",
                        "limitation_note": "not rerun for this descriptor",
                    },
                ]
            }
        ),
        encoding="utf-8",
    )
    return descriptor_path


def _write_stage_6_log(tmp_path: Path) -> Path:
    log_path = tmp_path / "market_maker.jsonl"
    write_jsonl_records(
        log_path,
        [
            {"record_type": "frame", "sequence": 1, "observed_at": "2026-06-24T00:00:00+00:00"},
            {
                "record_type": "quote_candidate",
                "sequence": 1,
                "instrument_id": "FED-TEST",
                "side": "buy",
                "price": "0.4100",
                "quantity": "1.00",
            },
            {"record_type": "risk_decision", "sequence": 1, "approved": True},
            {"record_type": "run_summary", "frame_count": 1, "quote_count": 1},
        ],
    )
    return log_path
