from __future__ import annotations

import json
from pathlib import Path

import pytest

from edmn_trader.data.jsonl import write_jsonl_records
from edmn_trader.scripts.paper_report_pack import (
    PaperReportPackInput,
    generate_paper_report_pack,
    main,
)

FIXTURES = Path(__file__).parent / "fixtures"


def test_paper_report_pack_combines_stage_7_metrics_and_sec_facts(tmp_path: Path) -> None:
    log_path = _write_stage_6_log(tmp_path)
    output_dir = tmp_path / "pack"
    manifest_path = _write_report_input_manifest(tmp_path)

    pack = generate_paper_report_pack(
        PaperReportPackInput(
            market_maker_logs=(log_path,),
            sec_companyfacts=(FIXTURES / "sec_companyfacts_aapl.json",),
            report_input_manifest=manifest_path,
            output_dir=output_dir,
        )
    )

    assert pack.stage7_report.supplied_fills == 0
    assert pack.sec_fact_count == 2
    assert pack.manifest_entry_count == 1
    text = (output_dir / "report_pack.md").read_text(encoding="utf-8")
    assert "Observed Stage 7 Attribution" in text
    assert "frames | 1" in text
    assert "Fill assumptions | not supplied" in text
    assert "Local Source Inventory" in text
    assert "market_maker.jsonl" in text
    assert "sec_companyfacts_aapl.json" in text
    assert "Report Input Manifest" in text
    assert "Local Stage 7 report" in text
    assert "local file generated by test" in text
    assert "SEC Fundamentals" in text
    assert "Apple Inc." in text
    assert "Revenues" in text
    assert "does not rank securities" in text
    assert "does not claim profitability" in text
    assert "trading signal" not in text.lower()


def test_paper_report_pack_marks_missing_sec_fundamentals_not_supplied(tmp_path: Path) -> None:
    output_dir = tmp_path / "pack"

    generate_paper_report_pack(
        PaperReportPackInput(
            market_maker_logs=(_write_stage_6_log(tmp_path),),
            output_dir=output_dir,
        )
    )

    text = (output_dir / "report_pack.md").read_text(encoding="utf-8")
    assert "SEC fundamentals | not supplied" in text
    assert "SEC companyfacts | not supplied" in text
    assert "Fills | not supplied" in text
    assert "Report input manifest | not supplied" in text
    assert "missing optional inputs are reported as not supplied" in text


def test_paper_report_pack_rejects_unsafe_manifest_inputs(tmp_path: Path) -> None:
    remote_manifest_path = _write_report_input_manifest(
        tmp_path,
        local_path="https://example.com/data.json",
    )
    with pytest.raises(ValueError, match="remote URL"):
        generate_paper_report_pack(
            PaperReportPackInput(
                market_maker_logs=(_write_stage_6_log(tmp_path),),
                report_input_manifest=remote_manifest_path,
                output_dir=tmp_path / "remote-pack",
            )
        )

    secret_manifest_path = _write_report_input_manifest(tmp_path, api_key="should-not-be-read")
    with pytest.raises(ValueError, match="secret-like"):
        generate_paper_report_pack(
            PaperReportPackInput(
                market_maker_logs=(_write_stage_6_log(tmp_path),),
                report_input_manifest=secret_manifest_path,
                output_dir=tmp_path / "pack",
            )
        )


def test_paper_report_pack_renders_local_run_comparison_input(tmp_path: Path) -> None:
    comparison_path = _write_run_comparison_descriptor(tmp_path)
    manifest_path = _write_report_input_manifest(
        tmp_path,
        local_path=comparison_path.name,
        input_kind="local_run_comparison",
        display_label="Local dry-run comparison",
    )
    output_dir = tmp_path / "pack"

    pack = generate_paper_report_pack(
        PaperReportPackInput(
            market_maker_logs=(_write_stage_6_log(tmp_path),),
            report_input_manifest=manifest_path,
            output_dir=output_dir,
        )
    )

    assert pack.run_comparison_count == 2
    text = (output_dir / "report_pack.md").read_text(encoding="utf-8")
    assert "Local Run Comparison" in text
    assert "baseline dry run" in text
    assert "demo opt-in dry run" in text
    assert "observed decisions" in text
    assert "fills" in text
    assert "local/offline comparison metadata only" in text
    assert "best run" not in text.lower()
    assert "recommend" not in text.lower()


def test_paper_report_pack_marks_missing_optional_run_comparison_not_supplied(
    tmp_path: Path,
) -> None:
    manifest_path = _write_report_input_manifest(
        tmp_path,
        local_path="missing-run-comparison.json",
        input_kind="local_run_comparison",
        display_label="Missing local comparison",
    )
    output_dir = tmp_path / "pack"

    generate_paper_report_pack(
        PaperReportPackInput(
            market_maker_logs=(_write_stage_6_log(tmp_path),),
            report_input_manifest=manifest_path,
            output_dir=output_dir,
        )
    )

    text = (output_dir / "report_pack.md").read_text(encoding="utf-8")
    assert "Local Run Comparison" in text
    assert "Missing local comparison | not supplied" in text


def test_paper_report_pack_rejects_unsafe_run_comparison_descriptor(tmp_path: Path) -> None:
    secret_descriptor_path = _write_run_comparison_descriptor(
        tmp_path,
        extra_run_field={"access_token": "should-not-be-read"},
    )
    secret_manifest_path = _write_report_input_manifest(
        tmp_path,
        local_path=secret_descriptor_path.name,
        input_kind="local_run_comparison",
    )
    with pytest.raises(ValueError, match="secret-like"):
        generate_paper_report_pack(
            PaperReportPackInput(
                market_maker_logs=(_write_stage_6_log(tmp_path),),
                report_input_manifest=secret_manifest_path,
                output_dir=tmp_path / "secret-pack",
            )
        )

    remote_descriptor_path = _write_run_comparison_descriptor(
        tmp_path,
        run_local_path="https://example.com/report.md",
    )
    remote_manifest_path = _write_report_input_manifest(
        tmp_path,
        local_path=remote_descriptor_path.name,
        input_kind="local_run_comparison",
    )
    with pytest.raises(ValueError, match="remote URL"):
        generate_paper_report_pack(
            PaperReportPackInput(
                market_maker_logs=(_write_stage_6_log(tmp_path),),
                report_input_manifest=remote_manifest_path,
                output_dir=tmp_path / "remote-comparison-pack",
            )
        )


def test_paper_report_pack_renders_local_validation_summary_input(tmp_path: Path) -> None:
    validation_path = _write_validation_summary_descriptor(tmp_path)
    manifest_path = _write_report_input_manifest(
        tmp_path,
        local_path=validation_path.name,
        input_kind="local_validation_summary",
        display_label="Local validation summary",
    )
    output_dir = tmp_path / "pack"

    pack = generate_paper_report_pack(
        PaperReportPackInput(
            market_maker_logs=(_write_stage_6_log(tmp_path),),
            report_input_manifest=manifest_path,
            output_dir=output_dir,
        )
    )

    assert pack.validation_summary_count == 2
    text = (output_dir / "report_pack.md").read_text(encoding="utf-8")
    assert "Local Validation Summary" in text
    assert "pytest" in text
    assert "ruff check ." in text
    assert "pass" in text
    assert "skipped" in text
    assert "pytest.log" in text
    assert "metadata about checks already run" in text
    assert "recommend" not in text.lower()


def test_paper_report_pack_marks_missing_optional_validation_summary_not_supplied(
    tmp_path: Path,
) -> None:
    manifest_path = _write_report_input_manifest(
        tmp_path,
        local_path="missing-validation-summary.json",
        input_kind="local_validation_summary",
        display_label="Missing validation summary",
    )
    output_dir = tmp_path / "pack"

    generate_paper_report_pack(
        PaperReportPackInput(
            market_maker_logs=(_write_stage_6_log(tmp_path),),
            report_input_manifest=manifest_path,
            output_dir=output_dir,
        )
    )

    text = (output_dir / "report_pack.md").read_text(encoding="utf-8")
    assert "Local Validation Summary" in text
    assert "Missing validation summary | not supplied" in text


def test_paper_report_pack_rejects_unsafe_validation_summary_descriptor(
    tmp_path: Path,
) -> None:
    secret_descriptor_path = _write_validation_summary_descriptor(
        tmp_path,
        extra_check_field={"api_secret": "should-not-be-read"},
    )
    secret_manifest_path = _write_report_input_manifest(
        tmp_path,
        local_path=secret_descriptor_path.name,
        input_kind="local_validation_summary",
    )
    with pytest.raises(ValueError, match="secret-like"):
        generate_paper_report_pack(
            PaperReportPackInput(
                market_maker_logs=(_write_stage_6_log(tmp_path),),
                report_input_manifest=secret_manifest_path,
                output_dir=tmp_path / "secret-validation-pack",
            )
        )

    remote_descriptor_path = _write_validation_summary_descriptor(
        tmp_path,
        artifact_path="https://example.com/pytest.log",
    )
    remote_manifest_path = _write_report_input_manifest(
        tmp_path,
        local_path=remote_descriptor_path.name,
        input_kind="local_validation_summary",
    )
    with pytest.raises(ValueError, match="remote URL"):
        generate_paper_report_pack(
            PaperReportPackInput(
                market_maker_logs=(_write_stage_6_log(tmp_path),),
                report_input_manifest=remote_manifest_path,
                output_dir=tmp_path / "remote-validation-pack",
            )
        )


def test_paper_report_pack_renders_local_review_notes_input(tmp_path: Path) -> None:
    review_notes_path = _write_review_notes_descriptor(tmp_path)
    manifest_path = _write_report_input_manifest(
        tmp_path,
        local_path=review_notes_path.name,
        input_kind="local_review_notes",
        display_label="Local review notes",
    )
    output_dir = tmp_path / "pack"

    pack = generate_paper_report_pack(
        PaperReportPackInput(
            market_maker_logs=(_write_stage_6_log(tmp_path),),
            report_input_manifest=manifest_path,
            output_dir=output_dir,
        )
    )

    assert pack.review_note_count == 2
    text = (output_dir / "report_pack.md").read_text(encoding="utf-8")
    assert "Local Review Notes" in text
    assert "input coverage caveat" in text
    assert "review-notes.json" in text
    assert "confirm optional inputs remain not supplied" in text
    assert "manual review context only" in text
    assert "recommend" not in text.lower()


def test_paper_report_pack_marks_missing_optional_review_notes_not_supplied(
    tmp_path: Path,
) -> None:
    manifest_path = _write_report_input_manifest(
        tmp_path,
        local_path="missing-review-notes.json",
        input_kind="local_review_notes",
        display_label="Missing review notes",
    )
    output_dir = tmp_path / "pack"

    generate_paper_report_pack(
        PaperReportPackInput(
            market_maker_logs=(_write_stage_6_log(tmp_path),),
            report_input_manifest=manifest_path,
            output_dir=output_dir,
        )
    )

    text = (output_dir / "report_pack.md").read_text(encoding="utf-8")
    assert "Local Review Notes" in text
    assert "Missing review notes | not supplied" in text


def test_paper_report_pack_rejects_unsafe_review_notes_descriptor(tmp_path: Path) -> None:
    secret_descriptor_path = _write_review_notes_descriptor(
        tmp_path,
        extra_note_field={"secret_token": "should-not-be-read"},
    )
    secret_manifest_path = _write_report_input_manifest(
        tmp_path,
        local_path=secret_descriptor_path.name,
        input_kind="local_review_notes",
    )
    with pytest.raises(ValueError, match="secret-like"):
        generate_paper_report_pack(
            PaperReportPackInput(
                market_maker_logs=(_write_stage_6_log(tmp_path),),
                report_input_manifest=secret_manifest_path,
                output_dir=tmp_path / "secret-review-pack",
            )
        )

    remote_descriptor_path = _write_review_notes_descriptor(
        tmp_path,
        source_path="https://example.com/private-note.md",
    )
    remote_manifest_path = _write_report_input_manifest(
        tmp_path,
        local_path=remote_descriptor_path.name,
        input_kind="local_review_notes",
    )
    with pytest.raises(ValueError, match="remote URL"):
        generate_paper_report_pack(
            PaperReportPackInput(
                market_maker_logs=(_write_stage_6_log(tmp_path),),
                report_input_manifest=remote_manifest_path,
                output_dir=tmp_path / "remote-review-pack",
            )
        )


def test_paper_report_pack_renders_local_methodology_notes_input(tmp_path: Path) -> None:
    methodology_notes_path = _write_methodology_notes_descriptor(tmp_path)
    manifest_path = _write_report_input_manifest(
        tmp_path,
        local_path=methodology_notes_path.name,
        input_kind="local_methodology_notes",
        display_label="Local methodology notes",
    )
    output_dir = tmp_path / "pack"

    pack = generate_paper_report_pack(
        PaperReportPackInput(
            market_maker_logs=(_write_stage_6_log(tmp_path),),
            report_input_manifest=manifest_path,
            output_dir=output_dir,
        )
    )

    assert pack.methodology_note_count == 2
    text = (output_dir / "report_pack.md").read_text(encoding="utf-8")
    assert "Local Methodology Notes" in text
    assert "baseline method" in text
    assert "methodology-notes.json" in text
    assert "descriptive methodology context only" in text
    assert "local/offline assumptions" in text
    assert "recommend" not in text.lower()


def test_paper_report_pack_marks_missing_optional_methodology_notes_not_supplied(
    tmp_path: Path,
) -> None:
    manifest_path = _write_report_input_manifest(
        tmp_path,
        local_path="missing-methodology-notes.json",
        input_kind="local_methodology_notes",
        display_label="Missing methodology notes",
    )
    output_dir = tmp_path / "pack"

    generate_paper_report_pack(
        PaperReportPackInput(
            market_maker_logs=(_write_stage_6_log(tmp_path),),
            report_input_manifest=manifest_path,
            output_dir=output_dir,
        )
    )

    text = (output_dir / "report_pack.md").read_text(encoding="utf-8")
    assert "Local Methodology Notes" in text
    assert "Missing methodology notes | not supplied" in text


def test_paper_report_pack_rejects_unsafe_methodology_notes_descriptor(
    tmp_path: Path,
) -> None:
    secret_descriptor_path = _write_methodology_notes_descriptor(
        tmp_path,
        extra_method_field={"private_key": "should-not-be-read"},
    )
    secret_manifest_path = _write_report_input_manifest(
        tmp_path,
        local_path=secret_descriptor_path.name,
        input_kind="local_methodology_notes",
    )
    with pytest.raises(ValueError, match="secret-like"):
        generate_paper_report_pack(
            PaperReportPackInput(
                market_maker_logs=(_write_stage_6_log(tmp_path),),
                report_input_manifest=secret_manifest_path,
                output_dir=tmp_path / "secret-methodology-pack",
            )
        )

    remote_descriptor_path = _write_methodology_notes_descriptor(
        tmp_path,
        source_path="https://example.com/methodology.md",
    )
    remote_manifest_path = _write_report_input_manifest(
        tmp_path,
        local_path=remote_descriptor_path.name,
        input_kind="local_methodology_notes",
    )
    with pytest.raises(ValueError, match="remote URL"):
        generate_paper_report_pack(
            PaperReportPackInput(
                market_maker_logs=(_write_stage_6_log(tmp_path),),
                report_input_manifest=remote_manifest_path,
                output_dir=tmp_path / "remote-methodology-pack",
            )
        )


def test_paper_report_pack_renders_local_data_dictionary_input(tmp_path: Path) -> None:
    data_dictionary_path = _write_data_dictionary_descriptor(tmp_path)
    manifest_path = _write_report_input_manifest(
        tmp_path,
        local_path=data_dictionary_path.name,
        input_kind="local_data_dictionary",
        display_label="Local data dictionary",
    )
    output_dir = tmp_path / "pack"

    pack = generate_paper_report_pack(
        PaperReportPackInput(
            market_maker_logs=(_write_stage_6_log(tmp_path),),
            report_input_manifest=manifest_path,
            output_dir=output_dir,
        )
    )

    assert pack.data_dictionary_field_count == 2
    text = (output_dir / "report_pack.md").read_text(encoding="utf-8")
    assert "Local Data Dictionary" in text
    assert "observed spread" in text
    assert "data-dictionary.json" in text
    assert "Decimal string" in text
    assert "percentage points" in text
    assert "local generated artifact" in text
    assert "recommend" not in text.lower()


def test_paper_report_pack_marks_missing_optional_data_dictionary_not_supplied(
    tmp_path: Path,
) -> None:
    manifest_path = _write_report_input_manifest(
        tmp_path,
        local_path="missing-data-dictionary.json",
        input_kind="local_data_dictionary",
        display_label="Missing data dictionary",
    )
    output_dir = tmp_path / "pack"

    generate_paper_report_pack(
        PaperReportPackInput(
            market_maker_logs=(_write_stage_6_log(tmp_path),),
            report_input_manifest=manifest_path,
            output_dir=output_dir,
        )
    )

    text = (output_dir / "report_pack.md").read_text(encoding="utf-8")
    assert "Local Data Dictionary" in text
    assert "Missing data dictionary | not supplied" in text


def test_paper_report_pack_rejects_unsafe_data_dictionary_descriptor(
    tmp_path: Path,
) -> None:
    secret_descriptor_path = _write_data_dictionary_descriptor(
        tmp_path,
        extra_field_metadata={"access_token": "should-not-be-read"},
    )
    secret_manifest_path = _write_report_input_manifest(
        tmp_path,
        local_path=secret_descriptor_path.name,
        input_kind="local_data_dictionary",
    )
    with pytest.raises(ValueError, match="secret-like"):
        generate_paper_report_pack(
            PaperReportPackInput(
                market_maker_logs=(_write_stage_6_log(tmp_path),),
                report_input_manifest=secret_manifest_path,
                output_dir=tmp_path / "secret-data-dictionary-pack",
            )
        )

    remote_descriptor_path = _write_data_dictionary_descriptor(
        tmp_path,
        source_path="https://example.com/raw-data.csv",
    )
    remote_manifest_path = _write_report_input_manifest(
        tmp_path,
        local_path=remote_descriptor_path.name,
        input_kind="local_data_dictionary",
    )
    with pytest.raises(ValueError, match="remote URL"):
        generate_paper_report_pack(
            PaperReportPackInput(
                market_maker_logs=(_write_stage_6_log(tmp_path),),
                report_input_manifest=remote_manifest_path,
                output_dir=tmp_path / "remote-data-dictionary-pack",
            )
        )


def test_paper_report_pack_renders_local_citation_index_input(tmp_path: Path) -> None:
    citation_index_path = _write_citation_index_descriptor(tmp_path)
    manifest_path = _write_report_input_manifest(
        tmp_path,
        local_path=citation_index_path.name,
        input_kind="local_citation_index",
        display_label="Local citation index",
    )
    output_dir = tmp_path / "pack"

    pack = generate_paper_report_pack(
        PaperReportPackInput(
            market_maker_logs=(_write_stage_6_log(tmp_path),),
            report_input_manifest=manifest_path,
            output_dir=output_dir,
        )
    )

    assert pack.citation_index_entry_count == 2
    text = (output_dir / "report_pack.md").read_text(encoding="utf-8")
    assert "Local Citation Index" in text
    assert "stage7 attribution report" in text
    assert "citation-index.json" in text
    assert "support observed metrics section" in text
    assert "local generated artifact" in text
    assert "recommend" not in text.lower()


def test_paper_report_pack_marks_missing_optional_citation_index_not_supplied(
    tmp_path: Path,
) -> None:
    manifest_path = _write_report_input_manifest(
        tmp_path,
        local_path="missing-citation-index.json",
        input_kind="local_citation_index",
        display_label="Missing citation index",
    )
    output_dir = tmp_path / "pack"

    generate_paper_report_pack(
        PaperReportPackInput(
            market_maker_logs=(_write_stage_6_log(tmp_path),),
            report_input_manifest=manifest_path,
            output_dir=output_dir,
        )
    )

    text = (output_dir / "report_pack.md").read_text(encoding="utf-8")
    assert "Local Citation Index" in text
    assert "Missing citation index | not supplied" in text


def test_paper_report_pack_rejects_unsafe_citation_index_descriptor(
    tmp_path: Path,
) -> None:
    secret_descriptor_path = _write_citation_index_descriptor(
        tmp_path,
        extra_citation_field={"secret_token": "should-not-be-read"},
    )
    secret_manifest_path = _write_report_input_manifest(
        tmp_path,
        local_path=secret_descriptor_path.name,
        input_kind="local_citation_index",
    )
    with pytest.raises(ValueError, match="secret-like"):
        generate_paper_report_pack(
            PaperReportPackInput(
                market_maker_logs=(_write_stage_6_log(tmp_path),),
                report_input_manifest=secret_manifest_path,
                output_dir=tmp_path / "secret-citation-index-pack",
            )
        )

    remote_descriptor_path = _write_citation_index_descriptor(
        tmp_path,
        source_path="https://example.com/source.pdf",
    )
    remote_manifest_path = _write_report_input_manifest(
        tmp_path,
        local_path=remote_descriptor_path.name,
        input_kind="local_citation_index",
    )
    with pytest.raises(ValueError, match="remote URL"):
        generate_paper_report_pack(
            PaperReportPackInput(
                market_maker_logs=(_write_stage_6_log(tmp_path),),
                report_input_manifest=remote_manifest_path,
                output_dir=tmp_path / "remote-citation-index-pack",
            )
        )

    excerpt_descriptor_path = _write_citation_index_descriptor(
        tmp_path,
        extra_citation_field={"excerpt": "private source contents"},
    )
    excerpt_manifest_path = _write_report_input_manifest(
        tmp_path,
        local_path=excerpt_descriptor_path.name,
        input_kind="local_citation_index",
    )
    with pytest.raises(ValueError, match="source-content"):
        generate_paper_report_pack(
            PaperReportPackInput(
                market_maker_logs=(_write_stage_6_log(tmp_path),),
                report_input_manifest=excerpt_manifest_path,
                output_dir=tmp_path / "excerpt-citation-index-pack",
            )
        )


def test_paper_report_pack_renders_local_term_glossary_input(tmp_path: Path) -> None:
    term_glossary_path = _write_term_glossary_descriptor(tmp_path)
    manifest_path = _write_report_input_manifest(
        tmp_path,
        local_path=term_glossary_path.name,
        input_kind="local_term_glossary",
        display_label="Local term glossary",
    )
    output_dir = tmp_path / "pack"

    pack = generate_paper_report_pack(
        PaperReportPackInput(
            market_maker_logs=(_write_stage_6_log(tmp_path),),
            report_input_manifest=manifest_path,
            output_dir=output_dir,
        )
    )

    assert pack.term_glossary_entry_count == 2
    text = (output_dir / "report_pack.md").read_text(encoding="utf-8")
    assert "Local Term Glossary" in text
    assert "observed spread" in text
    assert "term-glossary.json" in text
    assert "yes ask minus best yes bid" in text
    assert "report metrics only" in text
    assert "recommend" not in text.lower()


def test_paper_report_pack_marks_missing_optional_term_glossary_not_supplied(
    tmp_path: Path,
) -> None:
    manifest_path = _write_report_input_manifest(
        tmp_path,
        local_path="missing-term-glossary.json",
        input_kind="local_term_glossary",
        display_label="Missing term glossary",
    )
    output_dir = tmp_path / "pack"

    generate_paper_report_pack(
        PaperReportPackInput(
            market_maker_logs=(_write_stage_6_log(tmp_path),),
            report_input_manifest=manifest_path,
            output_dir=output_dir,
        )
    )

    text = (output_dir / "report_pack.md").read_text(encoding="utf-8")
    assert "Local Term Glossary" in text
    assert "Missing term glossary | not supplied" in text


def test_paper_report_pack_rejects_unsafe_term_glossary_descriptor(
    tmp_path: Path,
) -> None:
    secret_descriptor_path = _write_term_glossary_descriptor(
        tmp_path,
        extra_term_field={"private_key": "should-not-be-read"},
    )
    secret_manifest_path = _write_report_input_manifest(
        tmp_path,
        local_path=secret_descriptor_path.name,
        input_kind="local_term_glossary",
    )
    with pytest.raises(ValueError, match="secret-like"):
        generate_paper_report_pack(
            PaperReportPackInput(
                market_maker_logs=(_write_stage_6_log(tmp_path),),
                report_input_manifest=secret_manifest_path,
                output_dir=tmp_path / "secret-term-glossary-pack",
            )
        )

    remote_descriptor_path = _write_term_glossary_descriptor(
        tmp_path,
        source_path="https://example.com/glossary.md",
    )
    remote_manifest_path = _write_report_input_manifest(
        tmp_path,
        local_path=remote_descriptor_path.name,
        input_kind="local_term_glossary",
    )
    with pytest.raises(ValueError, match="remote URL"):
        generate_paper_report_pack(
            PaperReportPackInput(
                market_maker_logs=(_write_stage_6_log(tmp_path),),
                report_input_manifest=remote_manifest_path,
                output_dir=tmp_path / "remote-term-glossary-pack",
            )
        )

    excerpt_descriptor_path = _write_term_glossary_descriptor(
        tmp_path,
        extra_term_field={"source_excerpt": "private source contents"},
    )
    excerpt_manifest_path = _write_report_input_manifest(
        tmp_path,
        local_path=excerpt_descriptor_path.name,
        input_kind="local_term_glossary",
    )
    with pytest.raises(ValueError, match="source-content"):
        generate_paper_report_pack(
            PaperReportPackInput(
                market_maker_logs=(_write_stage_6_log(tmp_path),),
                report_input_manifest=excerpt_manifest_path,
                output_dir=tmp_path / "excerpt-term-glossary-pack",
            )
        )


def test_paper_report_pack_cli_writes_markdown(tmp_path: Path, capsys, monkeypatch) -> None:
    output_dir = tmp_path / "pack"
    manifest_path = _write_report_input_manifest(tmp_path)
    monkeypatch.setattr(
        "sys.argv",
        [
            "paper_report_pack",
            "--market-maker-log",
            str(_write_stage_6_log(tmp_path)),
            "--sec-companyfacts",
            str(FIXTURES / "sec_companyfacts_aapl.json"),
            "--report-input-manifest",
            str(manifest_path),
            "--output-dir",
            str(output_dir),
        ],
    )

    main()

    assert (output_dir / "report_pack.md").exists()
    output = capsys.readouterr().out
    assert "report_pack_output=" in output
    assert "sec_facts=2" in output
    assert "manifest_inputs=1" in output


def _write_report_input_manifest(
    tmp_path: Path,
    *,
    local_path: str = "stage7_attribution.md",
    input_kind: str = "stage7_report",
    display_label: str = "Local Stage 7 report",
    api_key: str | None = None,
) -> Path:
    manifest_path = tmp_path / "manifest.json"
    entry = {
        "local_path": local_path,
        "input_kind": input_kind,
        "display_label": display_label,
        "rights_note": "local file generated by test",
        "assumption_scope": "descriptive only",
        "required": False,
    }
    if api_key is not None:
        entry["api_key"] = api_key
    manifest_path.write_text(
        json.dumps(
            {
                "inputs": [entry]
            }
        ),
        encoding="utf-8",
    )
    return manifest_path


def _write_run_comparison_descriptor(
    tmp_path: Path,
    *,
    run_local_path: str = "stage7_attribution.md",
    extra_run_field: dict[str, str] | None = None,
) -> Path:
    descriptor_path = tmp_path / "run_comparison.json"
    first_run = {
        "run_name": "baseline dry run",
        "local_path": run_local_path,
        "observed_decision_count": 3,
        "not_supplied_inputs": ["fills"],
        "limitation_note": "local/offline comparison metadata only",
    }
    if extra_run_field:
        first_run.update(extra_run_field)
    descriptor_path.write_text(
        json.dumps(
            {
                "runs": [
                    first_run,
                    {
                        "run_name": "demo opt-in dry run",
                        "local_path": "report_pack.md",
                        "observed_decision_count": 4,
                        "not_supplied_inputs": [],
                        "limitation_note": "fake adapter only",
                    },
                ]
            }
        ),
        encoding="utf-8",
    )
    return descriptor_path


def _write_validation_summary_descriptor(
    tmp_path: Path,
    *,
    artifact_path: str = "pytest.log",
    extra_check_field: dict[str, str] | None = None,
) -> Path:
    descriptor_path = tmp_path / "validation_summary.json"
    first_check = {
        "command_label": "pytest",
        "status": "pass",
        "artifact_path": artifact_path,
        "observed_at": "2026-06-24T22:00:00-07:00",
        "limitation_note": "metadata about checks already run",
    }
    if extra_check_field:
        first_check.update(extra_check_field)
    descriptor_path.write_text(
        json.dumps(
            {
                "checks": [
                    first_check,
                    {
                        "command_label": "ruff check .",
                        "status": "skipped",
                        "artifact_path": "ruff.log",
                        "observed_at": "2026-06-24T22:01:00-07:00",
                        "limitation_note": "not rerun for this descriptor",
                    },
                ]
            }
        ),
        encoding="utf-8",
    )
    return descriptor_path


def _write_review_notes_descriptor(
    tmp_path: Path,
    *,
    source_path: str = "review-notes.json",
    extra_note_field: dict[str, str] | None = None,
) -> Path:
    descriptor_path = tmp_path / "review_notes.json"
    first_note = {
        "note_label": "input coverage caveat",
        "source_path": source_path,
        "note_text": "manual review context only",
        "follow_up_question": "confirm optional inputs remain not supplied",
        "limitation_note": "not investment advice",
    }
    if extra_note_field:
        first_note.update(extra_note_field)
    descriptor_path.write_text(
        json.dumps(
            {
                "notes": [
                    first_note,
                    {
                        "note_label": "assumption caveat",
                        "source_path": "review-notes.json",
                        "note_text": "fills are supplied assumptions only",
                        "follow_up_question": "",
                        "limitation_note": "descriptive only",
                    },
                ]
            }
        ),
        encoding="utf-8",
    )
    return descriptor_path


def _write_methodology_notes_descriptor(
    tmp_path: Path,
    *,
    source_path: str = "methodology-notes.json",
    extra_method_field: dict[str, str] | None = None,
) -> Path:
    descriptor_path = tmp_path / "methodology_notes.json"
    first_method = {
        "method_label": "baseline method",
        "source_path": source_path,
        "methodology_text": "descriptive methodology context only",
        "assumption_scope": "local/offline assumptions",
        "limitation_note": "not investment advice",
    }
    if extra_method_field:
        first_method.update(extra_method_field)
    descriptor_path.write_text(
        json.dumps(
            {
                "methods": [
                    first_method,
                    {
                        "method_label": "fill assumption method",
                        "source_path": "methodology-notes.json",
                        "methodology_text": "fills are supplied explicitly",
                        "assumption_scope": "hypothetical local fills only",
                        "limitation_note": "descriptive only",
                    },
                ]
            }
        ),
        encoding="utf-8",
    )
    return descriptor_path


def _write_data_dictionary_descriptor(
    tmp_path: Path,
    *,
    source_path: str = "data-dictionary.json",
    extra_field_metadata: dict[str, str] | None = None,
) -> Path:
    descriptor_path = tmp_path / "data_dictionary.json"
    first_field = {
        "field_label": "observed spread",
        "source_path": source_path,
        "data_type_label": "Decimal string",
        "unit": "percentage points",
        "definition": "observed yes ask minus best yes bid",
        "rights_sensitivity_label": "local generated artifact",
        "limitation_note": "descriptive field metadata only",
    }
    if extra_field_metadata:
        first_field.update(extra_field_metadata)
    descriptor_path.write_text(
        json.dumps(
            {
                "fields": [
                    first_field,
                    {
                        "field_label": "bid depth",
                        "source_path": "data-dictionary.json",
                        "data_type_label": "Decimal string",
                        "unit": "contracts",
                        "definition": "summed local fixture bid quantity",
                        "rights_sensitivity_label": "local fixture metadata",
                        "limitation_note": "not a live feed",
                    },
                ]
            }
        ),
        encoding="utf-8",
    )
    return descriptor_path


def _write_citation_index_descriptor(
    tmp_path: Path,
    *,
    source_path: str = "citation-index.json",
    extra_citation_field: dict[str, str] | None = None,
) -> Path:
    descriptor_path = tmp_path / "citation_index.json"
    first_citation = {
        "citation_label": "stage7 attribution report",
        "source_path": source_path,
        "citation_purpose": "support observed metrics section",
        "rights_note": "local generated artifact",
        "limitation_note": "metadata only; no excerpt included",
    }
    if extra_citation_field:
        first_citation.update(extra_citation_field)
    descriptor_path.write_text(
        json.dumps(
            {
                "citations": [
                    first_citation,
                    {
                        "citation_label": "SEC companyfacts fixture",
                        "source_path": "citation-index.json",
                        "citation_purpose": "identify local fixture source",
                        "rights_note": "public fixture metadata",
                        "limitation_note": "not a live remote fetch",
                    },
                ]
            }
        ),
        encoding="utf-8",
    )
    return descriptor_path


def _write_term_glossary_descriptor(
    tmp_path: Path,
    *,
    source_path: str = "term-glossary.json",
    extra_term_field: dict[str, str] | None = None,
) -> Path:
    descriptor_path = tmp_path / "term_glossary.json"
    first_term = {
        "term_label": "observed spread",
        "source_path": source_path,
        "definition": "yes ask minus best yes bid",
        "usage_scope": "report metrics only",
        "limitation_note": "local terminology metadata only",
    }
    if extra_term_field:
        first_term.update(extra_term_field)
    descriptor_path.write_text(
        json.dumps(
            {
                "terms": [
                    first_term,
                    {
                        "term_label": "source inventory",
                        "source_path": "term-glossary.json",
                        "definition": "list of local files supplied to the report pack",
                        "usage_scope": "local/offline provenance context",
                        "limitation_note": "not data-rights advice",
                    },
                ]
            }
        ),
        encoding="utf-8",
    )
    return descriptor_path


def _write_stage_6_log(tmp_path: Path) -> Path:
    log_path = tmp_path / "market_maker.jsonl"
    write_jsonl_records(
        log_path,
        [
            {"record_type": "frame", "sequence": 1, "observed_at": "2026-06-24T00:00:00+00:00"},
            {
                "record_type": "quote_candidate",
                "sequence": 1,
                "instrument_id": "FED-TEST",
                "side": "buy",
                "price": "0.4100",
                "quantity": "1.00",
            },
            {"record_type": "risk_decision", "sequence": 1, "approved": True},
            {"record_type": "run_summary", "frame_count": 1, "quote_count": 1},
        ],
    )
    return log_path
