"""Kalshi Demo adapter helpers."""

from edmn_trader.adapters.kalshi.client import (
    KALSHI_DEMO_REST_BASE_URL,
    KalshiClientError,
    KalshiConfigurationError,
    KalshiDemoMarketDataClient,
    KalshiEmptyOrderBookError,
    KalshiHTTPError,
    KalshiResponseError,
    normalize_kalshi_market_metadata,
    validate_kalshi_identifier,
    validate_kalshi_market_identity,
)
from edmn_trader.adapters.kalshi.demo_connector import (
    KalshiDemoConnectorConfig,
    KalshiDemoConnectorError,
    KalshiDemoConnectorResult,
    KalshiDemoRequestPreview,
    load_kalshi_demo_auth_headers_from_env,
    preview_or_submit_kalshi_demo,
    write_kalshi_demo_result_jsonl,
)
from edmn_trader.adapters.kalshi.demo_reconciliation import (
    KalshiDemoOrderState,
    KalshiDemoReconciliationError,
    KalshiDemoReconciliationMismatch,
    KalshiDemoReconciliationState,
    append_kalshi_demo_reconciliation_jsonl,
    reconcile_kalshi_demo_events,
    require_demo_reconciliation_submit_eligible,
)
from edmn_trader.adapters.kalshi.orderbook import normalize_kalshi_orderbook_fp
from edmn_trader.adapters.kalshi.readonly_recorder import (
    KalshiReadOnlyOptInRequired,
    KalshiReadOnlyRecorderConfig,
    KalshiReadOnlyRecorderResult,
    record_kalshi_readonly_orderbook,
)
from edmn_trader.adapters.kalshi.ws_auth import (
    KALSHI_DEMO_API_KEY_ID_ENV,
    KALSHI_DEMO_PRIVATE_KEY_PATH_ENV,
    KALSHI_DEMO_WS_URL,
    KalshiWsAuthBlocked,
    KalshiWsAuthConfig,
    build_kalshi_ws_headers,
    load_kalshi_ws_auth_config_from_env,
)
from edmn_trader.adapters.kalshi.ws_recorder import (
    KalshiWsRecorderConfig,
    KalshiWsRecorderResult,
    record_kalshi_demo_ws_orderbook,
)

__all__ = [
    "KALSHI_DEMO_REST_BASE_URL",
    "KALSHI_DEMO_WS_URL",
    "KALSHI_DEMO_API_KEY_ID_ENV",
    "KALSHI_DEMO_PRIVATE_KEY_PATH_ENV",
    "KalshiClientError",
    "KalshiConfigurationError",
    "KalshiDemoConnectorConfig",
    "KalshiDemoConnectorError",
    "KalshiDemoConnectorResult",
    "KalshiDemoMarketDataClient",
    "KalshiDemoOrderState",
    "KalshiDemoRequestPreview",
    "KalshiDemoReconciliationError",
    "KalshiDemoReconciliationMismatch",
    "KalshiDemoReconciliationState",
    "KalshiEmptyOrderBookError",
    "KalshiHTTPError",
    "KalshiReadOnlyOptInRequired",
    "KalshiReadOnlyRecorderConfig",
    "KalshiReadOnlyRecorderResult",
    "KalshiResponseError",
    "KalshiWsAuthBlocked",
    "KalshiWsAuthConfig",
    "KalshiWsRecorderConfig",
    "KalshiWsRecorderResult",
    "append_kalshi_demo_reconciliation_jsonl",
    "build_kalshi_ws_headers",
    "load_kalshi_demo_auth_headers_from_env",
    "load_kalshi_ws_auth_config_from_env",
    "normalize_kalshi_orderbook_fp",
    "normalize_kalshi_market_metadata",
    "preview_or_submit_kalshi_demo",
    "validate_kalshi_identifier",
    "validate_kalshi_market_identity",
    "reconcile_kalshi_demo_events",
    "record_kalshi_readonly_orderbook",
    "record_kalshi_demo_ws_orderbook",
    "require_demo_reconciliation_submit_eligible",
    "write_kalshi_demo_result_jsonl",
]
